### ISSUE TITLE
Exceptions are preferred to asserts

### ISSUE THREAD

**Issue by naydef** [WebFreak001/McRcD#1]
I'm using this library to send commands to a game client. It works pretty much fine, except when one of the asserts fails. The complete program stops.

I think I'd be better if those can be caught, so I guess they can be converted to throw Exceptions?

**Comment by WebFreak001** [comment]
make a PR, should be just replacing `assert` with `enforce` - has been a long while since I wrote this code so it may contain further issues though.

**Comment by WebFreak001** [comment]
I have updated the code to better coding practices and added an integration test in CI.

Will release this as v2, even though the API has almost no changes, it may change a little in behavior and I don't want anyones apps using a 9 year old library to suddenly update if they depend on 1.x

**Comment by naydef** [comment]
Alright, thanks for the effort.
